config/routes.rb
Rails.application.routes.draw do
    get 'customer/home'

    get 'customer/popular'

    get 'customer/category/:category(.:format)' => 'customer#category', as: :show_category

    get 'customer/saved_items'

    get 'customer/twitter_callback' => 'customer#twitter_callback'
    
    get '/customer/save_item/:id(.:format)' => 'customer#save_item', as: :save_item

    get '/customer/unsave_item/:id(.:format)' => 'customer#unsave_item', as: :unsave_item

    get 'customer/logout' => 'customer#logout'

    get '/auth/twitter/callback', to: 'customer#twitter_callback', as: :twitter_callback

    post '/customer/newsletter'

    post '/customer/email_login'

    post '/customer/email_signup'

	root 'customer#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
end

app/models/email_user.rb
class EmailUser < User
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/models/saved_item.rb
class SavedItem < ApplicationRecord
end

app/models/twitter_user.rb
class TwitterUser < User
end

app/models/user.rb
class User < ApplicationRecord
    def self.find_or_create_from_twitter_auth_hash(auth_hash)
        user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
        user.update(
          twitter_id: auth_hash.id,
          username: auth_hash.info.nickname,
          password: auth_hash.credentials.token,
        )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :info, :error, :warning
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_filter :initialise
  require 'active_support'
  
  def home
    @email = params[:email]
    @error = params[:error]
    
    @title = "Customer - Home"
    @nav_header = "Home"
    
    @users = EmailUser.all
    flash[:alert] = ""
    messages = params[:notice]
    if messages != nil
      messages.each do |key, message|
        flash[:alert] << message 
      end
    end

    @saved_items = session[:saved_items]
    items = Item.all
    @populars = Item.select("*, (amount_saved+amount_bought) as popularity").where("id <=4").order("popularity DESC")
    @user = session[:user]
    # change from object to hash 
    @items = Array.new
    items.each do |item|
      @items.push(item.attributes)
    end
    # reduce saved items from items
    @saved_items.each do |saved|
      @items.delete_if {|item| item['id'] == saved['id']}
    end
    if @items.any? then @banner = @items[rand(@items.length)] else @banner = Hash.new end
  end
  
  def category
    @user = session[:user]
    @category = params[:category]
    @title = "Category"
    @nav_header = "Category - " + @category
    @category_items = Array.new
    items = Item.all
    items.each do |item| 
      if item.category == @category
        @category_items.push(item)
      end
    end
  end
  
  def save_item
    saved_items = session[:saved_items]
    @item = Item.find(params[:id])
    saved_items.push(@item)
    session[:saved_items] = saved_items
    redirect_to :controller => 'customer', :action => 'home'
  end
  
  def unsave_item
    saved_items = session[:saved_items]
    @item_id = params[:id].to_i
    saved_items.delete_if { |item| @item_id == item['id'] }
    session[:saved_items] = saved_items
    redirect_to :controller => 'customer', :action => 'saved_items'
  end
  
  def saved_items
    @user = session[:user]
    @title = "Saved Items"
    @nav_header = "Saved Items"
    @saved_items = session[:saved_items]
  end
  
  def popular
    @title = "Popular Items"
    @nav_header = "Popular"
    @user = session[:user]
    @populars = Item.select("*, (amount_saved+amount_bought) as popularity").order("popularity DESC")
   
  end
  
  def email_signup
    @username = params[:username]
    @email = params[:email]
    @re_password = params[:re_pass]
    @password = params[:pass]
    messages = Hash.new
    users = EmailUser.all
    error = false
    if @password != @re_password
      error = true
      messages[:password]="Password is not the same! <br>"
    end
    users.each do |user|
      if (user.username == @username)
        error = true
        messages[:username]="Username is already taken! <br>"
      end
      
      if (user.email == @email)
        error = true
        messages[:email]="Email has been registered! <br>"
      end
    end
    
    if error == false
      EmailUser.create({
        :username  => @username,
        :email  => @email,
        :password => Base64.encode64(@password)
      })
      messages[:signup]="Congratulatios! You have been successfully registered!"
    end
      
    redirect_to :controller => 'customer', :action => 'home', :notice => messages
  end
  
  def email_login
    @input = params[:input]
    @password = params[:pass]
    message = Hash.new
    message[:login]  = "Invalid Login"
    users = EmailUser.all
    users.each do |user| 
      if ((user.username == @input || user.email == @input) && Base64.decode64(user.password) == @password)
        session[:user] = user
        message[:login] = "Successful Login"
        break
      end
    end
    redirect_to :controller => 'customer', :action => 'home', :notice => message
  end
  
  def logout
    session.delete(:user)
    message = Hash.new
    message[:logout] = "You have logout successfully!"
    redirect_to :controller => 'customer', :action => 'home', :notice => message
  end
  
  def newsletter
    newsletters = Newsletter.all
    @email = params[:email]
    exist = false
    newsletters.each do |item|
      if item.email == @email
        exist = true
        break
      end
    end
    
    if !exist
      @newsletter = Newsletter.create({:email => @email })
      NewsletterMailer.welcome_email(@email).deliver_later
    end
    
    redirect_to :controller => 'customer', :action => 'home', :email => @email, :error => exist
  end

  def twitter_callback
    @user = User.find_or_create_from_twitter_auth_hash(auth_hash)
    session[:user] = @user
    redirect_to root_path
  end
 
  protected
 
  def auth_hash
    puts request.env['omniauth.auth']
  end
  
  private
  
  def initialise
    @categories = Collection.all
    session[:saved_items] ||= Array.new
    session[:user] ||= User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/_footer.html.erb
<p class="left-right-margin">&copy Vincent Pranata/ s3665858 </p>

app/views/customer/_header.html.erb
<%= render 'customer/side_menu' %>
<div class="row">
    <div class="container-fluid">
        <div class="nav navbar-nav navbar-left">
            <ul class="nav navbar-nav">
                <li><a class="fa fa-bars" onclick="openNav()"></a></li>
            </ul>
        </div>
        <div class="nav navbar-nav navbar-right" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a class="fa fa-shopping-bag" href="#" onclick = ""></a></li>
                <li>
                    <form class="navbar-form navbar-left" action"">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/customer/_login_form.html.erb
<div class="popup" id="loginForm">
  <a href="javascript:void(0)" class="closebtn" onclick="closeLoginForm()">&times;</a>
  <div class="popup-container">
    <%= form_tag :controller => 'customer', :action => 'email_login' do %>
      <h1>Login</h1>
      <label for="input"><b>Email/ Username</b></label>
      <%= text_field_tag('input', nil, :placeholder => "Enter Email/ Username", :required => true) %>

      <label for="pass"><b>Password</b></label>
      <%= password_field_tag('pass', nil, :placeholder => "Enter Password", :required => true) %>

      <%= button_tag('Login', :type => "submit", :class => "btn") %>
    <% end %>
    <a>Forgot Password</a>
  </div>
</div>

app/views/customer/_login_page.html.erb
<div class="popup" id="loginPage">
 <a href="javascript:void(0)" class="closebtn" onclick="closeLoginPage()">&times;</a>
  <div class='popup-container'>
   <h2>RMIT Fashion</h2>
   <h4>Quality is not an act but a habit.</h4>
   <button class="btn" onclick="openLoginForm()">Login</button>
   <%= form_tag url_for('/auth/twitter'), :method => :post, :local => true do %>
    <button type='submit' class="btn cancel"><h5 class="fa fa-twitter" aria-hidden="true">&nbsp Login with Twitter </h5></button>
   <% end %>
   <a onclick="openSignupForm()">Sign Up</a>
  </div>
</div>

app/views/customer/_side_menu.html.erb
<div id="mySidenav" class="sidenav">
 <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
 <h4 class="fa fa-user"> 
 <% if @user['id'] == nil %>
   <a onclick="openLoginPage()">&nbsp Login</a> 
  </h4>
  <% else %>
   &nbsp <%= @user['username'] %> </h4>
  <h4 class="fa fa-sign-out-alt"> 
   <%= link_to('&nbsp Logout'.html_safe, :controller => "customer", :action => "logout") %>
  </h4>
 <% end %>
 <%= render 'customer/login_page' %>
 <%= render 'customer/login_form' %>
 <%= render 'customer/signup_form' %>
 <h4 class="fa fa-home">
  <%= link_to('&nbsp Home'.html_safe, :controller => "customer", :action => "home") %>
 </h4>
 <h4 class="fa fa-tag"> &nbsp Shop </h4>
 <% @categories.each do |collection| %>
  <%= link_to(collection.name, show_category_path(collection.name)) %>
 <% end %>
 <h4 class="fa fa-heart">
  <%= link_to('&nbsp Saved'.html_safe, customer_saved_items_path()) %>
 </h4>
 <h4 class="fa fa-question-circle">
  <%= link_to('&nbsp Help & Support'.html_safe, :controller => "customer", :action => "home") %>
 </h4>
</div>

app/views/customer/_signup_form.html.erb
<div class="popup" id="signupForm">
  <a href="javascript:void(0)" class="closebtn" onclick="closeSignupForm()">&times;</a>
  <div class="popup-container">
    <%= form_tag :controller => 'customer', :action => 'email_signup' do %>
      <h1>Sign Up</h1>
      <label for="username"><b>Username</b></label>
      <%= text_field_tag('username', nil, :placeholder => "Enter Username", :required => true) %>

      <label for="email"><b>Email</b></label>
      <%= text_field_tag('email', nil, :placeholder => "Enter Email", :required => true) %>

      <label for="pass"><b>Password</b></label>
      <%= password_field_tag('pass', nil, :placeholder => "Enter Password", :required => true) %>

      <label for="re_pass"><b>Re-input Password</b></label>
      <%= password_field_tag('re_pass', nil, :placeholder => "Re-Enter Password", :required => true) %>

      <%= button_tag('Register', :type => "submit", :class => "btn") %>
    <% end %>
    <a onclick="openLoginForm()">Login</a>
  </div>
</div>

app/views/customer/category.html.erb
<% content_for :title, @title %>
<% content_for :nav_header, @nav_header %>

<% content_for :navbar do %>
    <nav class="navbar navbar-default no-margin">
      <div class="navbar-header row no-margin">
        <p class="navbar-brand"><%= yield(:nav_header) %></p>
      </div>
      <%= render 'customer/header' %>	
    </nav>
<% end %>

<% content_for :items do %>
    <% @category_items.each do |item| %>
        <div class="col col-sm-3 margin-auto">
    	    <%= image_tag(item.image, :alt => item.name+" Icon") %>
            <h3><%= item.name %></h3>
        	<p>$<%= item.price %></p>
        </div>
    <% end %>
<% end %>

<% content_for :content do %>
    <div id="content" class="jumbotron no-padding">
        <div id="category_item" class="left-right-margin">
            <% if @category_items.any? %>
                <div class="container row no-margin">
                  <%= content_for?(:items) ? yield(:items) : yield %>
                </div>
            <% else %>
                <div class="empty-container">
                    <h3 class="center">There are no items of this category currently registered</h3>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/customer/home.html.erb
<% content_for :title, @title %>
<% content_for :nav_header, @nav_header %>

<% content_for :navbar do %>
  <nav class="navbar navbar-default no-margin">
    <div class="navbar-header row no-margin">
      <p class="navbar-brand"><%= yield(:nav_header) %></p>
    </div>
    <%= render 'customer/header' %>	
  </nav>
<% end %>

<% content_for :top_banner do %>
  <h3><%= @banner['name'] %></h3>
  <p>Cold & Brilliant Start</p>
	<p>$<%= @banner['price'] %></p>
<% end %>

<% content_for :populars do %>
    <% @populars.each do |item| %>
        <div class="col col-sm-3 margin-auto">
    	    <%= image_tag(item.image, :alt => item.name+" Icon") %>
            <h3><%= item.name %></h3>
        	<p>$<%= item.price %></p>
        </div>
    <% end %>
<% end %>

<% content_for :collections do %>
    <% @categories.each do |collection| %>
        <div class="col col-sm-3 margin-auto">
            <div class="card w-50">
                <div class="card-body">
                    <h4 class="card-title"><%= collection.name %></h5>
                    <p class="card-text"><%= collection.total_items %> items</p>
                    <%= link_to('All Items', show_category_path(collection.name), :class => "btn btn-primary") %>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

<% content_for :content do %>
    <% if flash != nil %>
        <div class="alert-info", style="max-height: 70px; padding: 5px 0px 0px 5px;">
            <% flash.each do |key, value| %>
                <%= value.html_safe %>
            <% end %>
        </div>
    <% end %>
    <div id="content" class="jumbotron no-padding">
      <div id="top-banner">
        <% if @banner.any? %>
          <div class="row left-right-margin" id="info">
            <%= content_for?(:top_banner) ? yield(:top_banner) : yield %>
      		</div>
          <div class="row left-right-margin" id="fav-icon">
            <%= link_to('<i class="fa fa-heart"></i>'.html_safe, save_item_path(@banner['id'])) %>
          </div>
        <% else %>
          <div class="center empty-container">
            <h3>There is no more items to be featured. You have saved all items</h3>
          </div>
        <% end %>
      </div>
      <div id="popular" class="left-right-margin">
        <div class = "flex-container">
          <h2>Popular</h2>
          <%= link_to('See all +', customer_popular_path()) %>
        </div>
        <div class="container row no-margin">
          <%= content_for?(:populars) ? yield(:populars) : yield %>
        </div>
      </div>
      <div id="collection" class="left-right-margin">
        <div class = "flex-container">
          <h2>Collections</h2>
          <%= link_to('See all +', customer_popular_path()) %>
        </div>
        <div class="container row no-margin">
          <%= content_for?(:collections) ? yield(:collections) : yield %>
        </div>
      </div>
      <div id="newsletter" class="left-right-margin">
        <h2>Newsletter</h2>
        <p>Signup to our newsletter</p>
        <div class="form">
          <%= form_tag :controller => 'customer', :action => 'newsletter' do %>
            <%= render 'shared/error_messages' %>
            <div class="input-group">
              <%= email_field_tag('email', @email, :class => "form-control", :placeholder => "Enter your Email", :required => true) %>
              <div class="input-group-btn">
                <%= button_tag('<i class="fa fa-angle-right"></i>'.html_safe, :type => "submit", :class => "btn btn-default") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/customer/popular.html.erb
<% content_for :title, @title %>
<% content_for :nav_header, @nav_header %>

<% content_for :navbar do %>
  <nav class="navbar navbar-default no-margin">
    <div class="navbar-header row no-margin">
      <p class="navbar-brand"><%= yield(:nav_header) %></p>
    </div>
    <%= render 'customer/header' %>	
  </nav>
<% end %>

<% content_for :populars do %>
    <% @populars.each do |item| %>
        <div class="col col-sm-3 margin-auto">
    	    <%= image_tag(item.image, :alt => item.name+" Icon") %>
            <h3><%= item.name %></h3>
        	<p>$<%= item.price %></p>
        </div>
    <% end %>
<% end %>

<% content_for :content do %>
    <div id="content" class="jumbotron no-padding">
      <div id="top-banner">
      </div>
      <div id="popular" class="left-right-margin">
       <div class="container row no-margin">
          <%= content_for?(:populars) ? yield(:populars) : yield %>
        </div>
      </div>
    </div>
<% end %>

app/views/customer/saved_items.html.erb
<% content_for :title, @title %>
<% content_for :nav_header, @nav_header %>

<% content_for :navbar do %>
  <nav class="navbar navbar-default no-margin">
    <div class="navbar-header row no-margin">
      <p class="navbar-brand"><%= yield(:nav_header) %></p>
    </div>
    <%= render 'customer/header' %>	
  </nav>
<% end %>

<% content_for :saved_items do %>
    <% if @saved_items.any?%>
      <% @saved_items.each do |item| %>
          <div class="col col-sm-3 margin-auto">
      	    <%= image_tag(item['image'], :alt => item['name']+" Icon") %>
              <h3><%= item['name'] %></h3>
          	<p>$<%= item['price'] %></p>
          	<%= link_to('<i class="fa fa-heart"></i>'.html_safe, unsave_item_path(item['id']), :style => "color: red;")%>
          </div>
      <% end %>
    <% else %>
      <div class="empty-container">
        <h3 class="center"> No items are currently being saved</h3>
      </div>
    <% end %>
<% end %>


<% content_for :content do %>
    <div id="content" class="jumbotron no-padding">
      <div id="top-banner">
      </div>
      <div id="saved_item" class="left-right-margin">
       <div class="container row no-margin">
          <%= content_for?(:saved_items) ? yield(:saved_items) : yield %>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_for?(:navbar) ? yield(:navbar) : yield %>
    <%= content_for?(:content) ? yield(:content) : yield %>
    <%= render 'customer/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @error == 'true' %>
    <div id="error_messages">
        <div class="alert alert-danger">
            Email is already subscribed to newsletter.
        </div>
    </div>
<% end %>
<% if @error == 'false' %>
    <div id="success_messages">
        <div class="alert alert-success">
            Congratulations! You are now subscribed to our newsletter.            
        </div>
    </div>
<% end %>